/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Date = IDL.Text;
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Order = IDL.Record({
  'design' : IDL.Text,
  'orderId' : IDL.Text,
  'product' : IDL.Text,
});
export const KarigarAssignment = IDL.Record({
  'karigar' : IDL.Text,
  'orderId' : IDL.Text,
  'factory' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignKarigar' : IDL.Func(
      [Date, IDL.Vec(IDL.Text), IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyOrders' : IDL.Func([Date], [IDL.Vec(Order)], ['query']),
  'getKarigarAssignments' : IDL.Func(
      [Date],
      [IDL.Vec(KarigarAssignment)],
      ['query'],
    ),
  'getKarigarForDesign' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getOrdersByKarigar' : IDL.Func(
      [Date, IDL.Text],
      [IDL.Vec(Order)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'parseKarigarMappingFile' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'storeDailyOrders' : IDL.Func([Date, IDL.Vec(Order)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Date = IDL.Text;
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Order = IDL.Record({
    'design' : IDL.Text,
    'orderId' : IDL.Text,
    'product' : IDL.Text,
  });
  const KarigarAssignment = IDL.Record({
    'karigar' : IDL.Text,
    'orderId' : IDL.Text,
    'factory' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignKarigar' : IDL.Func(
        [Date, IDL.Vec(IDL.Text), IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyOrders' : IDL.Func([Date], [IDL.Vec(Order)], ['query']),
    'getKarigarAssignments' : IDL.Func(
        [Date],
        [IDL.Vec(KarigarAssignment)],
        ['query'],
      ),
    'getKarigarForDesign' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getOrdersByKarigar' : IDL.Func(
        [Date, IDL.Text],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'parseKarigarMappingFile' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'storeDailyOrders' : IDL.Func([Date, IDL.Vec(Order)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };