/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyOrder {
  'weight' : string,
  'size' : string,
  'design' : string,
  'orderNo' : string,
  'quantity' : string,
  'remarks' : string,
}
export type Date = string;
export type ExternalBlob = Uint8Array;
export interface KarigarAssignment {
  'karigar' : string,
  'orderId' : string,
  'factory' : [] | [string],
}
export interface KarigarMapping {
  'karigar' : string,
  'designPattern' : string,
  'factory' : [] | [string],
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignKarigar' : ActorMethod<
    [Date, Array<string>, string, [] | [string]],
    undefined
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyOrders' : ActorMethod<[Date], Array<DailyOrder>>,
  'getKarigarAssignments' : ActorMethod<[Date], Array<KarigarAssignment>>,
  'getKarigarMappingWorkbook' : ActorMethod<[], [] | [ExternalBlob]>,
  'getKarigarMappings' : ActorMethod<[], Array<[string, KarigarMapping]>>,
  'getOrdersByKarigar' : ActorMethod<[Date, string], Array<DailyOrder>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveKarigarMappingWorkbook' : ActorMethod<[ExternalBlob], undefined>,
  'storeDailyOrders' : ActorMethod<[Date, Array<DailyOrder>], undefined>,
  'storeKarigarMappings' : ActorMethod<[Array<KarigarMapping>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];