/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Date = IDL.Text;
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DailyOrder = IDL.Record({
  'weight' : IDL.Text,
  'size' : IDL.Text,
  'design' : IDL.Text,
  'orderNo' : IDL.Text,
  'quantity' : IDL.Text,
  'remarks' : IDL.Text,
});
export const KarigarAssignment = IDL.Record({
  'karigar' : IDL.Text,
  'orderId' : IDL.Text,
  'factory' : IDL.Opt(IDL.Text),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const KarigarMapping = IDL.Record({
  'karigar' : IDL.Text,
  'designPattern' : IDL.Text,
  'factory' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignKarigar' : IDL.Func(
      [Date, IDL.Vec(IDL.Text), IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyOrders' : IDL.Func([Date], [IDL.Vec(DailyOrder)], ['query']),
  'getKarigarAssignments' : IDL.Func(
      [Date],
      [IDL.Vec(KarigarAssignment)],
      ['query'],
    ),
  'getKarigarMappingWorkbook' : IDL.Func(
      [],
      [IDL.Opt(ExternalBlob)],
      ['query'],
    ),
  'getKarigarMappings' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, KarigarMapping))],
      ['query'],
    ),
  'getOrdersByKarigar' : IDL.Func(
      [Date, IDL.Text],
      [IDL.Vec(DailyOrder)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveKarigarMappingWorkbook' : IDL.Func([ExternalBlob], [], []),
  'storeDailyOrders' : IDL.Func([Date, IDL.Vec(DailyOrder)], [], []),
  'storeKarigarMappings' : IDL.Func([IDL.Vec(KarigarMapping)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Date = IDL.Text;
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DailyOrder = IDL.Record({
    'weight' : IDL.Text,
    'size' : IDL.Text,
    'design' : IDL.Text,
    'orderNo' : IDL.Text,
    'quantity' : IDL.Text,
    'remarks' : IDL.Text,
  });
  const KarigarAssignment = IDL.Record({
    'karigar' : IDL.Text,
    'orderId' : IDL.Text,
    'factory' : IDL.Opt(IDL.Text),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const KarigarMapping = IDL.Record({
    'karigar' : IDL.Text,
    'designPattern' : IDL.Text,
    'factory' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignKarigar' : IDL.Func(
        [Date, IDL.Vec(IDL.Text), IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyOrders' : IDL.Func([Date], [IDL.Vec(DailyOrder)], ['query']),
    'getKarigarAssignments' : IDL.Func(
        [Date],
        [IDL.Vec(KarigarAssignment)],
        ['query'],
      ),
    'getKarigarMappingWorkbook' : IDL.Func(
        [],
        [IDL.Opt(ExternalBlob)],
        ['query'],
      ),
    'getKarigarMappings' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, KarigarMapping))],
        ['query'],
      ),
    'getOrdersByKarigar' : IDL.Func(
        [Date, IDL.Text],
        [IDL.Vec(DailyOrder)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveKarigarMappingWorkbook' : IDL.Func([ExternalBlob], [], []),
    'storeDailyOrders' : IDL.Func([Date, IDL.Vec(DailyOrder)], [], []),
    'storeKarigarMappings' : IDL.Func([IDL.Vec(KarigarMapping)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };